from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from app.auth.context import get_tenant_id
from app.services.reasoning import intellectus_brain
from langchain_core.messages import HumanMessage

router = APIRouter(prefix="/chat", tags=["chat"])

@router.post("")
async def chat_interaction(payload: dict, tenant_ctx: dict = Depends(get_tenant_id)):
    user_input = payload["messages"][-1]["content"]
    tenant_id = tenant_ctx["tenant_id"]

    async def stream_generator():
        # Initialize graph state
        inputs = {
            "messages": [HumanMessage(content=user_input)],
            "tenant_id": tenant_id
        }
        
        # Stream the graph execution
        async for event in intellectus_brain.astream_events(inputs, version="v2"):
            kind = event["event"]
            
            # Filter for actual text chunks generated by the model
            if kind == "on_chat_model_stream":
                content = event["data"]["chunk"].content
                if content:
                    yield content

    return StreamingResponse(stream_generator(), media_type="text/event-stream")